from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
import os


def generate_report(symptoms, disease, info):

    # Create reports folder if it doesn't exist
    os.makedirs("reports", exist_ok=True)

    # Handle missing disease information
    if info is None:
        info = {
            "description": "No description available for this disease.",
            "precautions": [
                "Consult a qualified healthcare professional.",
                "Follow medical advice."
            ],
            "diet": [
                "Eat a balanced diet.",
                "Drink plenty of water."
            ],
            "doctor": "Please consult a healthcare professional for proper diagnosis."
        }

    filename = f"reports/{disease.replace(' ', '_')}_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    # ----------------------------------------------------
    # Title
    # ----------------------------------------------------
    story.append(
        Paragraph("MediSense AI Health Report", styles["Title"])
    )

    story.append(
        Paragraph(
            f"Generated on: {datetime.now().strftime('%d-%m-%Y %I:%M %p')}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 15))

    # ----------------------------------------------------
    # Disease
    # ----------------------------------------------------
    story.append(
        Paragraph("Predicted Disease", styles["Heading2"])
    )

    story.append(
        Paragraph(disease, styles["Normal"])
    )

    story.append(Spacer(1, 15))

    # ----------------------------------------------------
    # Symptoms
    # ----------------------------------------------------
    story.append(
        Paragraph("Selected Symptoms", styles["Heading2"])
    )

    for symptom in symptoms:
        story.append(
            Paragraph(
                f"• {symptom.replace('_', ' ').title()}",
                styles["Normal"]
            )
        )

    story.append(Spacer(1, 15))

    # ----------------------------------------------------
    # Description
    # ----------------------------------------------------
    story.append(
        Paragraph("Description", styles["Heading2"])
    )

    story.append(
        Paragraph(info.get("description", "Not Available"), styles["Normal"])
    )

    story.append(Spacer(1, 10))

    # ----------------------------------------------------
    # Precautions
    # ----------------------------------------------------
    story.append(
        Paragraph("Precautions", styles["Heading2"])
    )

    for precaution in info.get("precautions", []):
        story.append(
            Paragraph(f"• {precaution}", styles["Normal"])
        )

    story.append(Spacer(1, 10))

    # ----------------------------------------------------
    # Diet
    # ----------------------------------------------------
    story.append(
        Paragraph("Diet Recommendations", styles["Heading2"])
    )

    for item in info.get("diet", []):
        story.append(
            Paragraph(f"• {item}", styles["Normal"])
        )

    story.append(Spacer(1, 10))

    # ----------------------------------------------------
    # Doctor Advice
    # ----------------------------------------------------
    story.append(
        Paragraph("Doctor Advice", styles["Heading2"])
    )

    story.append(
        Paragraph(
            info.get("doctor", "Consult a doctor."),
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Disclaimer:</b> This report is generated by MediSense AI "
            "for educational purposes only and should not replace professional medical advice.",
            styles["Italic"]
        )
    )

    doc.build(story)

    return filename